### ISSUE TITLE
lodash 3.x breaking changes.

### ISSUE THREAD

**Issue by LyndonArmitage** [TomNeyland/angular-dc#30]
Lodash recently released their [3+ version](https://github.com/lodash/lodash/releases) which causes issues with a project I am working on.

It appears that the dimension and group attributes do not bind properly when using lodash version 3+

A proposed solution would be to changed the current bower.json dependency to something using the tilde (~2 should be sufficient assuming lodash do not insert any breaking changes later).

A workaround I am using is to specfically give a dependency version in our projects bower.json:
    "lodash": "2.4.1"

**Comment by TomNeyland** [comment]
Thanks for pointing this out, fixed in 14b275343d8de5b757a10581f895d2e1de89de0f, and tagged a new release.
