### ISSUE TITLE
Multi line Chart

### ISSUE THREAD

**Issue by dulcetti** [TomNeyland/angular-dc#46]
I trying generate a lineChart with multiple lines, but I couldn't. On example of Nasdaq don't have a multiple line, but on example of dc.js exist.

It's possible?

**Comment by ruhley** [comment]
This is called a [series chart](https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#series-chart)

**Comment by dulcetti** [comment]
Hmm, okay, thanks, I will look that. I think if there were an example of Series Chart at Readme of Angular-DC it would be great.

Regards
