### ISSUE TITLE
Get the specific Chart

### ISSUE THREAD

**Issue by dulcetti** [TomNeyland/angular-dc#49]
Hi, on DC.

Dc.js I can get the chart:
var myChart = dc.lineChart('#my-chart');

But how can I do on angular-dc inside the Controller? I need to put a link to reset a specific Chart out of html of Chart.

Regards.

**Comment by dulcetti** [comment]
Relax, I got it.

Regards.

**Comment by idanb11** [comment]
Hi @dulcetti ,
Can you show how you did it?

**Comment by dulcetti** [comment]
@idanb11 hey man. Sorry for the late response. When you commented, I was don't haven't access on the code of company =/
